export const metadata = {
	title: 'OpenTable | Search',
	description: 'Generated by create next app',
};

export default function SearchLayout({ children }: { children: React.ReactNode }) {
	return <>{children}</>;
}
